# version: '3'
services:
  llama_factory-dev:
    build:
      context: ../../
      dockerfile: docker/docker-dev/Dockerfile
    image: llama_factory-dev:0.0.1
    runtime: nvidia
    # command: []
    # ports:
    #   - "8082:8082"
    container_name: llama_factory-dev
    tty: true
    shm_size: 8g
    restart: always
    ulimits:
      memlock: -1
      stack: 67108864
    volumes:
      - /data1/zhangjl:/workspace
      - /data1/zhangjl/softs/.vscode-server:/root/.vscode-server

      